### ISSUE TITLE
Rework app theming

### ISSUE THREAD

**Issue by chrisbouchard** [chrisbouchard/upliftinglemma-net#6]
Dynamic SCSS (or even CSS) is not going to work in Rails. It goes against the whole idea of the asset pipeline and precompilation. How should we let apps theme themselves?

Right now, we can load the theme for an app well enough. The `themes/<app-slug>.scss` file sets some variables then pulls in `theme.scss` to do the heavy-lifting. The problem is that, if one app wants to use colors from another app, it would have to pull down the other app's *entire* theme, which would certainly conflict. For example, the Uplifting Lemma app wants to use all the other apps' primary colors to create links.

One option would be to switch to straight CSS for theming. We could create hooks, e.g., classes like 

* `theme-primary-color`
* `theme-primary-background`

Each app would get a namespacing class as well, e.g., `app-uplifting-lemma`. So the theme for Uplifting Lemma could look like:
```CSS
.app-uplifting-lemma.theme-primary-color {
    color: hsl(240, 43%, 37%);
}

.app-uplifting-lemma.theme-primary-background {
    background-color: hsl(240, 43%, 37%);
}
```
Each color-related hook would need to have `*-color` and `*-background` variants. SCSS variables could make this less painful. CSS variables could too, but I don't know how much support there is in current browsers.
